# Generated by Django 5.2.4 on 2025-09-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('reviewtext', models.CharField(max_length=100)),
                ('rating', models.IntegerField(max_length=5)),
            ],
        ),
    ]
