# Generated by Django 5.2.4 on 2025-10-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='upload_photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
